// Copyright 2026 CloseClaw Authors. All rights reserved.
// CloseClaw Ultra — 三语言异构微内核跨进程通信契约 (P027)
// syntax = proto3, 向前兼容保留字段 100-199

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: messages.proto

package clawpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelBus_DispatchTask_FullMethodName       = "/closeclaw.v1.KernelBus/DispatchTask"
	KernelBus_SyncStatus_FullMethodName         = "/closeclaw.v1.KernelBus/SyncStatus"
	KernelBus_CheckHealth_FullMethodName        = "/closeclaw.v1.KernelBus/CheckHealth"
	KernelBus_GetPendingMessages_FullMethodName = "/closeclaw.v1.KernelBus/GetPendingMessages"
	KernelBus_SubscribeTasks_FullMethodName     = "/closeclaw.v1.KernelBus/SubscribeTasks"
	KernelBus_Chat_FullMethodName               = "/closeclaw.v1.KernelBus/Chat"
)

// KernelBusClient is the client API for KernelBus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KernelBusClient interface {
	// 核心任务流
	DispatchTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskResponse, error)
	SyncStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*Ack, error)
	CheckHealth(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 消息与订阅
	GetPendingMessages(ctx context.Context, in *Ack, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingMessage], error)
	SubscribeTasks(ctx context.Context, in *Ack, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error)
	// LLM 推理转发 (Phase 3B)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type kernelBusClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelBusClient(cc grpc.ClientConnInterface) KernelBusClient {
	return &kernelBusClient{cc}
}

func (c *kernelBusClient) DispatchTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, KernelBus_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelBusClient) SyncStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, KernelBus_SyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelBusClient) CheckHealth(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, KernelBus_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelBusClient) GetPendingMessages(ctx context.Context, in *Ack, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelBus_ServiceDesc.Streams[0], KernelBus_GetPendingMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ack, IncomingMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBus_GetPendingMessagesClient = grpc.ServerStreamingClient[IncomingMessage]

func (c *kernelBusClient) SubscribeTasks(ctx context.Context, in *Ack, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelBus_ServiceDesc.Streams[1], KernelBus_SubscribeTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ack, Task]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBus_SubscribeTasksClient = grpc.ServerStreamingClient[Task]

func (c *kernelBusClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, KernelBus_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelBusServer is the server API for KernelBus service.
// All implementations must embed UnimplementedKernelBusServer
// for forward compatibility.
type KernelBusServer interface {
	// 核心任务流
	DispatchTask(context.Context, *Task) (*TaskResponse, error)
	SyncStatus(context.Context, *StatusUpdate) (*Ack, error)
	CheckHealth(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 消息与订阅
	GetPendingMessages(*Ack, grpc.ServerStreamingServer[IncomingMessage]) error
	SubscribeTasks(*Ack, grpc.ServerStreamingServer[Task]) error
	// LLM 推理转发 (Phase 3B)
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	mustEmbedUnimplementedKernelBusServer()
}

// UnimplementedKernelBusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelBusServer struct{}

func (UnimplementedKernelBusServer) DispatchTask(context.Context, *Task) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedKernelBusServer) SyncStatus(context.Context, *StatusUpdate) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncStatus not implemented")
}
func (UnimplementedKernelBusServer) CheckHealth(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedKernelBusServer) GetPendingMessages(*Ack, grpc.ServerStreamingServer[IncomingMessage]) error {
	return status.Error(codes.Unimplemented, "method GetPendingMessages not implemented")
}
func (UnimplementedKernelBusServer) SubscribeTasks(*Ack, grpc.ServerStreamingServer[Task]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTasks not implemented")
}
func (UnimplementedKernelBusServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedKernelBusServer) mustEmbedUnimplementedKernelBusServer() {}
func (UnimplementedKernelBusServer) testEmbeddedByValue()                   {}

// UnsafeKernelBusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelBusServer will
// result in compilation errors.
type UnsafeKernelBusServer interface {
	mustEmbedUnimplementedKernelBusServer()
}

func RegisterKernelBusServer(s grpc.ServiceRegistrar, srv KernelBusServer) {
	// If the following call panics, it indicates UnimplementedKernelBusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelBus_ServiceDesc, srv)
}

func _KernelBus_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelBusServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelBus_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelBusServer).DispatchTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelBus_SyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelBusServer).SyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelBus_SyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelBusServer).SyncStatus(ctx, req.(*StatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelBus_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelBusServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelBus_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelBusServer).CheckHealth(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelBus_GetPendingMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Ack)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelBusServer).GetPendingMessages(m, &grpc.GenericServerStream[Ack, IncomingMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBus_GetPendingMessagesServer = grpc.ServerStreamingServer[IncomingMessage]

func _KernelBus_SubscribeTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Ack)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelBusServer).SubscribeTasks(m, &grpc.GenericServerStream[Ack, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelBus_SubscribeTasksServer = grpc.ServerStreamingServer[Task]

func _KernelBus_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelBusServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelBus_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelBusServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelBus_ServiceDesc is the grpc.ServiceDesc for KernelBus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelBus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "closeclaw.v1.KernelBus",
	HandlerType: (*KernelBusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _KernelBus_DispatchTask_Handler,
		},
		{
			MethodName: "SyncStatus",
			Handler:    _KernelBus_SyncStatus_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _KernelBus_CheckHealth_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _KernelBus_Chat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPendingMessages",
			Handler:       _KernelBus_GetPendingMessages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTasks",
			Handler:       _KernelBus_SubscribeTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messages.proto",
}
