// Copyright 2026 CloseClaw Authors. All rights reserved.
// CloseClaw Ultra — 三语言异构微内核跨进程通信契约 (P027)
// syntax = proto3, 向前兼容保留字段 100-199

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: messages.proto

package clawpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus 对应 src/db.ts scheduled_tasks.is_paused 语义，并扩展了分布式状态
type TaskStatus int32

const (
	TaskStatus_PENDING TaskStatus = 0
	TaskStatus_RUNNING TaskStatus = 1
	TaskStatus_DONE    TaskStatus = 2
	TaskStatus_FAILED  TaskStatus = 3
	TaskStatus_TIMEOUT TaskStatus = 4 // Dart 层心跳超时时标记，触发 L2 降级
	TaskStatus_PAUSED  TaskStatus = 5 // 对应 is_paused = 1，沿用 TS 层的调度暂停概念
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "DONE",
		3: "FAILED",
		4: "TIMEOUT",
		5: "PAUSED",
	}
	TaskStatus_value = map[string]int32{
		"PENDING": 0,
		"RUNNING": 1,
		"DONE":    2,
		"FAILED":  3,
		"TIMEOUT": 4,
		"PAUSED":  5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// TraceContext 由 Dart 控制层在接收用户消息时生成，
// 必须透传到所有下游 Go / TS 调用链，形成全链路追踪票据。
type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                // UUID v4，Dart 端生成
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`                   // 当前操作 span（可选）
	CreatedAtMs   int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"` // 毫秒时间戳，用于端到端延迟计算
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TraceContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceContext) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceContext) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

// Task 携带从 Dart 层下发至 Go 内核的全量业务信息。
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Trace         *TraceContext          `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`
	GroupJid      string                 `protobuf:"bytes,3,opt,name=group_jid,json=groupJid,proto3" json:"group_jid,omitempty"`
	GroupFolder   string                 `protobuf:"bytes,4,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON 序列化的动态参数
	Status        TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=closeclaw.v1.TaskStatus" json:"status,omitempty"`
	ScheduleType  string                 `protobuf:"bytes,7,opt,name=schedule_type,json=scheduleType,proto3" json:"schedule_type,omitempty"`
	ScheduleValue string                 `protobuf:"bytes,8,opt,name=schedule_value,json=scheduleValue,proto3" json:"schedule_value,omitempty"`
	CreatedAtMs   int64                  `protobuf:"varint,9,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	NextRunAtMs   int64                  `protobuf:"varint,10,opt,name=next_run_at_ms,json=nextRunAtMs,proto3" json:"next_run_at_ms,omitempty"`
	// DAG 支持：依赖的任务 IDs (逗号分隔或 repeated)
	DependsOn     []string `protobuf:"bytes,11,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTrace() *TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Task) GetGroupJid() string {
	if x != nil {
		return x.GroupJid
	}
	return ""
}

func (x *Task) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_PENDING
}

func (x *Task) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *Task) GetScheduleValue() string {
	if x != nil {
		return x.ScheduleValue
	}
	return ""
}

func (x *Task) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *Task) GetNextRunAtMs() int64 {
	if x != nil {
		return x.NextRunAtMs
	}
	return 0
}

func (x *Task) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

// TaskResponse 由 Go 内核返回给 Dart 层，携带执行摘要。
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=closeclaw.v1.TaskStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ElapsedMs     int64                  `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_PENDING
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

// StatusUpdate 由 TS 沙盒完成工具调用后发送至 Go，回写结果。
type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=closeclaw.v1.TaskStatus" json:"status,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"` // 工具调用原始返回 JSON
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CompletedAtMs int64                  `protobuf:"varint,6,opt,name=completed_at_ms,json=completedAtMs,proto3" json:"completed_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *StatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatusUpdate) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StatusUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_PENDING
}

func (x *StatusUpdate) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StatusUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StatusUpdate) GetCompletedAtMs() int64 {
	if x != nil {
		return x.CompletedAtMs
	}
	return 0
}

// Ack 通用确认回执
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IncomingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	ChatJid       string                 `protobuf:"bytes,3,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	SenderJid     string                 `protobuf:"bytes,4,opt,name=sender_jid,json=senderJid,proto3" json:"sender_jid,omitempty"`
	SenderName    string                 `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsGroup       bool                   `protobuf:"varint,8,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	GroupName     string                 `protobuf:"bytes,9,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Processed     bool                   `protobuf:"varint,10,opt,name=processed,proto3" json:"processed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingMessage) Reset() {
	*x = IncomingMessage{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessage) ProtoMessage() {}

func (x *IncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessage.ProtoReflect.Descriptor instead.
func (*IncomingMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *IncomingMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncomingMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *IncomingMessage) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *IncomingMessage) GetSenderJid() string {
	if x != nil {
		return x.SenderJid
	}
	return ""
}

func (x *IncomingMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *IncomingMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IncomingMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IncomingMessage) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *IncomingMessage) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *IncomingMessage) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SentAtMs      int64                  `protobuf:"varint,2,opt,name=sent_at_ms,json=sentAtMs,proto3" json:"sent_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HeartbeatRequest) GetSentAtMs() int64 {
	if x != nil {
		return x.SentAtMs
	}
	return 0
}

type HeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	QueueLength      int32                  `protobuf:"varint,2,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`
	ActiveGoroutines int32                  `protobuf:"varint,3,opt,name=active_goroutines,json=activeGoroutines,proto3" json:"active_goroutines,omitempty"`
	KernelVersion    string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetQueueLength() int32 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *HeartbeatResponse) GetActiveGoroutines() int32 {
	if x != nil {
		return x.ActiveGoroutines
	}
	return 0
}

func (x *HeartbeatResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HeartbeatResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         *TraceContext          `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	History       []string               `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`                                                                           // 简化为字符串数组，后续可扩展
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 模型选择、温度等参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ChatRequest) GetTrace() *TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=closeclaw.v1.TaskStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ChatResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_PENDING
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\fcloseclaw.v1\"f\n" +
	"\fTraceContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\"\x91\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x05trace\x18\x02 \x01(\v2\x1a.closeclaw.v1.TraceContextR\x05trace\x12\x1b\n" +
	"\tgroup_jid\x18\x03 \x01(\tR\bgroupJid\x12!\n" +
	"\fgroup_folder\x18\x04 \x01(\tR\vgroupFolder\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.closeclaw.v1.TaskStatusR\x06status\x12#\n" +
	"\rschedule_type\x18\a \x01(\tR\fscheduleType\x12%\n" +
	"\x0eschedule_value\x18\b \x01(\tR\rscheduleValue\x12\"\n" +
	"\rcreated_at_ms\x18\t \x01(\x03R\vcreatedAtMs\x12#\n" +
	"\x0enext_run_at_ms\x18\n" +
	" \x01(\x03R\vnextRunAtMs\x12\x1d\n" +
	"\n" +
	"depends_on\x18\v \x03(\tR\tdependsOn\"\x91\x02\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x06status\x18\b \x01(\x0e2\x18.closeclaw.v1.TaskStatusR\x06status\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12D\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2(.closeclaw.v1.TaskResponse.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\fStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.closeclaw.v1.TaskStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12&\n" +
	"\x0fcompleted_at_ms\x18\x06 \x01(\x03R\rcompletedAtMs\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x02\n" +
	"\x0fIncomingMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x19\n" +
	"\bchat_jid\x18\x03 \x01(\tR\achatJid\x12\x1d\n" +
	"\n" +
	"sender_jid\x18\x04 \x01(\tR\tsenderJid\x12\x1f\n" +
	"\vsender_name\x18\x05 \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bis_group\x18\b \x01(\bR\aisGroup\x12\x1d\n" +
	"\n" +
	"group_name\x18\t \x01(\tR\tgroupName\x12\x1c\n" +
	"\tprocessed\x18\n" +
	" \x01(\bR\tprocessed\"K\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\n" +
	"sent_at_ms\x18\x02 \x01(\x03R\bsentAtMs\"\xc1\x01\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fqueue_length\x18\x02 \x01(\x05R\vqueueLength\x12+\n" +
	"\x11active_goroutines\x18\x03 \x01(\x05R\x10activeGoroutines\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\"\xf1\x01\n" +
	"\vChatRequest\x120\n" +
	"\x05trace\x18\x01 \x01(\v2\x1a.closeclaw.v1.TraceContextR\x05trace\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\ahistory\x18\x03 \x03(\tR\ahistory\x12@\n" +
	"\aoptions\x18\x04 \x03(\v2&.closeclaw.v1.ChatRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\fChatResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.closeclaw.v1.TaskStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*U\n" +
	"\n" +
	"TaskStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x052\x9c\x03\n" +
	"\tKernelBus\x12>\n" +
	"\fDispatchTask\x12\x12.closeclaw.v1.Task\x1a\x1a.closeclaw.v1.TaskResponse\x12;\n" +
	"\n" +
	"SyncStatus\x12\x1a.closeclaw.v1.StatusUpdate\x1a\x11.closeclaw.v1.Ack\x12N\n" +
	"\vCheckHealth\x12\x1e.closeclaw.v1.HeartbeatRequest\x1a\x1f.closeclaw.v1.HeartbeatResponse\x12H\n" +
	"\x12GetPendingMessages\x12\x11.closeclaw.v1.Ack\x1a\x1d.closeclaw.v1.IncomingMessage0\x01\x129\n" +
	"\x0eSubscribeTasks\x12\x11.closeclaw.v1.Ack\x1a\x12.closeclaw.v1.Task0\x01\x12=\n" +
	"\x04Chat\x12\x19.closeclaw.v1.ChatRequest\x1a\x1a.closeclaw.v1.ChatResponseB\x1fZ\x1dcloseclaw/kernel/proto;clawpbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_messages_proto_goTypes = []any{
	(TaskStatus)(0),           // 0: closeclaw.v1.TaskStatus
	(*TraceContext)(nil),      // 1: closeclaw.v1.TraceContext
	(*Task)(nil),              // 2: closeclaw.v1.Task
	(*TaskResponse)(nil),      // 3: closeclaw.v1.TaskResponse
	(*StatusUpdate)(nil),      // 4: closeclaw.v1.StatusUpdate
	(*Ack)(nil),               // 5: closeclaw.v1.Ack
	(*IncomingMessage)(nil),   // 6: closeclaw.v1.IncomingMessage
	(*HeartbeatRequest)(nil),  // 7: closeclaw.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 8: closeclaw.v1.HeartbeatResponse
	(*ChatRequest)(nil),       // 9: closeclaw.v1.ChatRequest
	(*ChatResponse)(nil),      // 10: closeclaw.v1.ChatResponse
	nil,                       // 11: closeclaw.v1.TaskResponse.MetadataEntry
	nil,                       // 12: closeclaw.v1.ChatRequest.OptionsEntry
}
var file_messages_proto_depIdxs = []int32{
	1,  // 0: closeclaw.v1.Task.trace:type_name -> closeclaw.v1.TraceContext
	0,  // 1: closeclaw.v1.Task.status:type_name -> closeclaw.v1.TaskStatus
	0,  // 2: closeclaw.v1.TaskResponse.status:type_name -> closeclaw.v1.TaskStatus
	11, // 3: closeclaw.v1.TaskResponse.metadata:type_name -> closeclaw.v1.TaskResponse.MetadataEntry
	0,  // 4: closeclaw.v1.StatusUpdate.status:type_name -> closeclaw.v1.TaskStatus
	1,  // 5: closeclaw.v1.ChatRequest.trace:type_name -> closeclaw.v1.TraceContext
	12, // 6: closeclaw.v1.ChatRequest.options:type_name -> closeclaw.v1.ChatRequest.OptionsEntry
	0,  // 7: closeclaw.v1.ChatResponse.status:type_name -> closeclaw.v1.TaskStatus
	2,  // 8: closeclaw.v1.KernelBus.DispatchTask:input_type -> closeclaw.v1.Task
	4,  // 9: closeclaw.v1.KernelBus.SyncStatus:input_type -> closeclaw.v1.StatusUpdate
	7,  // 10: closeclaw.v1.KernelBus.CheckHealth:input_type -> closeclaw.v1.HeartbeatRequest
	5,  // 11: closeclaw.v1.KernelBus.GetPendingMessages:input_type -> closeclaw.v1.Ack
	5,  // 12: closeclaw.v1.KernelBus.SubscribeTasks:input_type -> closeclaw.v1.Ack
	9,  // 13: closeclaw.v1.KernelBus.Chat:input_type -> closeclaw.v1.ChatRequest
	3,  // 14: closeclaw.v1.KernelBus.DispatchTask:output_type -> closeclaw.v1.TaskResponse
	5,  // 15: closeclaw.v1.KernelBus.SyncStatus:output_type -> closeclaw.v1.Ack
	8,  // 16: closeclaw.v1.KernelBus.CheckHealth:output_type -> closeclaw.v1.HeartbeatResponse
	6,  // 17: closeclaw.v1.KernelBus.GetPendingMessages:output_type -> closeclaw.v1.IncomingMessage
	2,  // 18: closeclaw.v1.KernelBus.SubscribeTasks:output_type -> closeclaw.v1.Task
	10, // 19: closeclaw.v1.KernelBus.Chat:output_type -> closeclaw.v1.ChatResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
