name: Codacy Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4.4.7
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: false
          max-allowed-issues: 2147483647
