name: CodeScene

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codescene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CodeScene Analysis
        uses: empear-analytics/codescene-ci-cd@v1.3.3
        continue-on-error: true
        with:
          codescene-enterprise-token: ${{ secrets.CODESCENE_ENTERPRISE_TOKEN }}
