name: CodeScene

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codescene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CodeScene Analysis
        uses: codescene-io/codescene-ci-cd@v2
        continue-on-error: true
        with:
          codescene-enterprise-token: ${{ secrets.CODESCENE_ENTERPRISE_TOKEN }}
