name: Quality Gate - Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dart-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Dart Analyze
        run: |
          cd cmd
          dart analyze
